on: push
name: Tests suite

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Common tests setup
        uses: ./.github/actions/tests-common

      - name: Setup dependencies
        run: make docker-deps

      - name: Execute tests
        run: make docker-test

  lint:
    name: Automated linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Common tests setup
        uses: ./.github/actions/tests-common

      - name: Setup dependencies
        run: make docker-deps

      - run: make docker-lint

  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Common tests setup
        uses: ./.github/actions/tests-common

      - name: Setup dependencies
        run: make docker-deps

      - run: make docker-dialyzer
